#!/usr/bin/env python
# Build: scons platform=windows target=template_debug custom_api_file=api/extension_api.json
# (see BUILD.md; the api/ dump pins godot-cpp master to the Godot 4.7 stable API)
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "../addons/worldgen/bin/worldgen_native{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
Default(library)
