@tool
class_name FxFireStyle
extends FxStyle
## Every STATIC lever of the FIRE effect — the cover field, the noise that carves it, the ramp it is
## coloured from, and HOW FAST EACH OF THEM RAMPS AS STACKS RISE. Read by `fire.gdshader` and by
## `FxFire`.
##
## Variants are .tres files, not code: `fire_card` / `fire_prop` / `fire_ball` today, frost or poison
## later with no new shader. Editing one retunes a running game.
##
## ⚠ THIRTEEN KNOBS RETIRED HERE ON 2026-07-29 with the tendril model (owner: *"Fire effect no longer
## has tendrils at all, just average fire shader effects like moving noise instead"*): `height_var`,
## `base_width`, `ogee_point`, `ogee_flare`, `onion_power`, `onion_rise`, `merge`, `sway_amp`,
## `sway_speed`, `wave_amp`, `wave_freq`, `wave_speed`, `desync`. They described a comb of individual
## arches, and there is no comb. The noise knobs below do their job with four mask lookups instead of
## eleven — see `fire.gdshader`'s header and FX_HANDOFF §9 for why the two changes only pay together.
##
## What is NOT here is the juggling pattern (`FxJuggleStyle`), and that separation is the point: a
## fire style has no use for `ball_radius`, and showing both halves made every resource read like the
## union of two unrelated things (owner 2026-07-31). See `FxStyle` for why this is a subclass rather
## than a flag.

## The baked seamless tile the texture noise path samples. Re-roll it with
## `py solatro/tools/make_fx_noise.py`; it is committed rather than generated by `NoiseTexture2D`
## because that generates on a worker thread at LOAD, and a rendering test with a race in it is not
## a test.
const NOISE_TILE := preload("res://Assets/Fx/noise_fire.png")

@export_group("Pixels")
## Bayer dither strength on band edges — breaks the edge without softening it.
@export_range(0.0, 1.0, 0.01) var dither : float = 0.0

@export_group("Coverage")
## THE REACH: how far above a surface the fire can possibly be, in art units. It is a HARD bound —
## the cover taps span exactly this and no further — so it is also exactly how far past the host's
## silhouette the quad has to reach.
##
## For a CARD-hosted effect the budget is half the default card separation —
## `CardVisual.CARD_SEPARATION * 0.5` = 7 — so the flames never reach the card behind and cover it
## (owner 2026-07-28). Prop-hosted styles are in PROP art units (screen pixels at the default
## card_scale, ~2.5x smaller), so their number is not the same number.
@export var height : float = 7.0
## ⚠ THE COST KNOB, AND THE ONLY ONE THAT MATTERS. This shader is `mask_level` call count times cost
## per call and nothing else: it is linear at ~0.48 ms per tap per full screen of burning cards
## (FX_HANDOFF §9), so 4 -> 6 is +50 % on the dominant term.
##
## 4 taps over a 7-unit reach is 1.75-unit resolution, and the noise hides the banding that leaves —
## which is the whole reason the tendrils had to go before the march could (a tendril needed the
## surface located to 0.4 units, ~11 taps; noise does not). Raise it only with `01_fire_ladder`
## open side by side, and re-run `fx_cost.tscn` after.
@export_range(2, 8, 1) var cover_taps : int = 4
## How much of one tap step the ladder's phase is dithered by, per FX pixel.
##
## ⚠ **THIS IS WHAT STOPS `cover_taps` FROM BEING VISIBLE AS HARD CONCENTRIC SHELLS.** `cover` takes
## only `taps + 1` values and the ramp is `filter_nearest`, so at 0 every one of them is a flat band
## with a hard edge, ringing the whole silhouette. 1 is a full step and dissolves the staircase into
## a gradient for the price of one hash — no extra taps, which is the only cost that matters here.
## Turn it to 0 only to LOOK at the raw ladder (`00_cover_field` does exactly that).
@export_range(0.0, 1.0, 0.01) var cover_dither : float = 1.0
## HOW FAR THE FIRE IS ALLOWED DOWN INTO THE HOST'S ART, in art units — the encroachment knob
## (owner 2026-07-29). Positive sinks the base below the surface, which is what guarantees no seam
## where flame meets host; 0 plants it exactly on the surface; NEGATIVE lifts it clear so the flames
## sit above the art and cover nothing at all.
##
## This is the lever for "the fire is hiding my card", NOT `inner_alpha`. Fire is opaque — every
## shipped style sets `inner_alpha = 1.0`, because seeing the art through the flame reads badly — so
## the only thing that decides how much art a flame covers is how far down its base starts.
@export_range(-16.0, 16.0, 0.25) var sink : float = 2.0
## Opacity where the effect overlays the host's body — i.e. **whether the fire draws IN FRONT OF the
## art or gets out of its way.**
##
## ⚠ **EVERY SHIPPED STYLE SETS THIS TO 0.0** (owner 2026-07-29: *"I would prefer that fire effect
## always be behind main card art visually, so it never covers art and hides jaggedness of fire
## bottom vs object tops when rotating or warping"*). At 0 the flame is cut exactly at the host's
## mask, so:
##  * it covers no art at all, at any rotation or warp;
##  * the seam between flame and host becomes the HOST'S OWN outline rather than the flame's ragged
##    foot, which is the "hides jaggedness" half of the request;
##  * and `sink` stops being about how much art is covered and becomes how much of the flame's base
##    is BURIED — how far below the visible seam the noise gets to do its work unseen. Every style
##    now runs a positive sink for that reason.
##
## The value in between is a genuine setting for a future effect that should be see-through (a ghost,
## a frost bloom); 1.0 is the old behaviour, where fire painted over its host.
##
## ⚠ **IT IS A PERFORMANCE KNOB TOO.** At exactly 1.0 the shader skips the extra mask lookup that
## answers "am I over the body", on a uniform branch. Anything else pays one lookup per LIT fragment
## — measured at well under a tap, because lit fragments are the minority.
##
## ⚠ **THIS IS NOT TRUE DRAW-ORDER OCCLUSION**, and the difference matters in exactly one place. The
## cut follows the MASK, and the mask is what the fire reads — for a card at rest that IS the art's
## outline exactly, but a WARPED card's mask is a 32-ray scale field interpolating a 16-point
## polygon, so the two can disagree by a fraction of a pixel between rays. Real occlusion would mean
## putting the fire quad BEFORE `visual` in the tree (LAYERING.md's `move_child`, never a z_index) —
## which needs a SECOND `FxAttachment`, because a juggling card's balls must stay in FRONT of it
## (ruling 11) and one attachment is one sibling. Not done; see FX_HANDOFF §0i.3.
##
## ⚠ **THE DEFAULT IS 0, AND THAT IS DELIBERATE ROBUSTNESS.** Godot omits any property equal to its
## script default when it saves a `.tres`, so a value that has to be non-default to be correct is one
## the editor can silently drop — and it dropped this one from `fire_prop.tres` twice while this
## script was being edited (FX_HANDOFF §11's collision, §0i.5). Making the wanted behaviour the
## DEFAULT means a clobbered resource still comes back right.
@export_range(0.0, 1.0, 0.01) var inner_alpha : float = 0.0

@export_group("Flame shape")
## THE APERTURE — the one knob the whole look turns on (Fire Shader by Yui Kinomoto @arlez80, MIT:
## `noise = UV.y * (((UV.y + aperture) * fire_noise - aperture) * 75.0)`).
##
## ⚠ **IT IS A CUT, NOT AN OPENING, and the first draft of this doc had it backwards.** At average
## noise the shaped value is `0.5 * gain * cover * (cover - aperture)`, which is zero at
## `cover = aperture` — so this is literally **the cover threshold below which nothing burns**:
##  * **LOW** (0.1) — a solid body of fire filling its whole reach, barely touched by the noise;
##  * **MID** (0.35) — the shipped feel: a ragged, hole-punched flame;
##  * **HIGH** (0.9) — eaten back to a few flecks at the base, wherever the brightest noise pushes
##    through.
## `fx_snapshot`'s `00b_aperture` is those three panels side by side.
@export_range(0.0, 1.0, 0.01) var aperture : float = 0.35
## Contrast on the shaped value before it is clamped into the ramp. Low leaves a soft gradient over
## the whole flame; high slams most of it to the hot end and leaves only a thin cool rim.
@export_range(0.25, 8.0, 0.05) var fire_gain : float = 2.2
## Outward lean of the crown: the flame is sheared away from centre in proportion to how far out it
## sits (owner ruling 1's "some angle skew as spread"). It grows with height above the surface, so
## the base stays planted on the body and only the top moves.
@export_range(0.0, 1.0, 0.01) var skew : float = 0.15

@export_group("Motion")
## Whole-effect breathing, on the APERTURE — so a breathing flame grows and shrinks rather than
## flashing. Kept separate from brightness so photosensitivity can be reduced independently.
@export var pulse_amp : float = 0.0
@export var pulse_speed : float = 2.0
## How hard the flames trail the host's motion (the cape).
@export_range(0.0, 2.0, 0.01) var lag_amount : float = 1.0
## One vector biasing the lean.
@export var wind : Vector2 = Vector2.ZERO

@export_group("Texture")
## How far the noise swings either side of flat — and it is the knob the whole flame's raggedness
## comes from, so it is the first one to reach for when the fire reads as slabs.
##
## ⚠ 0 is a real setting, not a disabled one: it gives a clean cover field with no grain at all,
## which is how the geometry snapshots see the shape on its own. **1 reaches the full 0..1 range**
## with a little clipping at each end, and the clipping is wanted — it is what gives fire solid cores
## and clean cutoffs. `fire_noise` carries the contrast gain that makes that true; measured, the raw
## two-layer noise only spans 0.215..0.786 on its own, so a plain lerp toward flat could never get
## there.
@export_range(0.0, 1.0, 0.01) var noise_amp : float = 0.8
## Grain size, and how fast the grain RISES up the flame.
@export var noise_scale : float = 0.35
@export var noise_scroll : float = 18.0
## THE SECOND NOISE LAYER, relative to the first: `noise_ratio` is its grain, `flicker_speed` its
## speed. Two layers at different scales AND speeds is what stops noise reading as a texture sliding
## past — it is the one idea kept from the owner's tri-colour reference.
##
## ⚠ `noise_ratio = 0` DROPS THE SECOND LAYER WHOLE, and that is a PERFORMANCE setting as much as a
## look one: the layer is about a third of the noise cost, and the noise is the second most
## expensive thing in the shader after the cover field. It is the compromise to reach for on a
## machine that cannot afford it — but it is visible, so judge `01_fire_ladder` before and after.
@export var noise_ratio : float = 2.1
@export var flicker_speed : float = 1.7
## ⚠ WHICH NOISE SOURCE, AND THIS EXISTS TO BE MEASURED (FX_HANDOFF §0e.1). On = `fx_fbm`, three
## octaves of hash+lerp per fragment. Off = one fetch from the baked seamless tile below, whose
## octaves were paid for at import.
##
## It trades seven ALU taps for one memory fetch, and on an Intel UHD with shared memory bandwidth
## which of those wins is genuinely not obvious — `Tests/Visual/fx_cost.tscn` prices both rows, and
## the shipped default is whichever won there. It is a UNIFORM branch, so it costs nothing to carry
## both. This is not a noise-TYPE system: there is one alternative, not an enum.
@export var noise_procedural : bool = true
## The tile the texture path samples, and the art units one full repeat of it covers. Swap the
## texture to A/B a different grain live in the FX editor; ⚠ CHECK THE REPEAT BY EYE at the shipped
## `noise_scale` — a nearest-filtered scrolling tile repeats visibly if its period lands near the
## flame height, and no number catches that.
@export var noise_tex : Texture2D = NOISE_TILE
@export var noise_tile : float = 32.0

@export_group("Stack scaling")
## HOW FAST EACH KNOB RAMPS AS STACKS RISE (owner 2026-07-29: *"just increasing shader params as
## intensity/stacks increase... make sure all params have scaling ratios as stacks increase"*).
##
## Every one is a multiplier on `log(stacks)`, applied in ONE place — `FxFire.stacks_live` — as
## `value * (1 + log(stacks) * ratio)`. Two properties this shape is chosen for, and both are
## requirements rather than preferences:
##  * **CONTINUOUS AND MONOTONE IN THE COUNT** (owner ruling 16: a stack change eases, it never
##    jumps). `FxAttachment._eased` can only tween what is continuous, and a knob that stepped at
##    integer stacks would make the whole effect pop.
##  * **LOGARITHMIC, so it never saturates.** 100 stacks should look terrifying, not 100 times
##    brighter than one — and there is no cap anywhere in the pipeline (owner ruling 4).
##
## ⚠ AT ONE STACK EVERY RATIO IS INERT (`log(1) = 0`), so the base values above are exactly what a
## single stack looks like. Tune the base at 1 stack, then tune the ramp at 40 and 200.
## Negative is meaningful: `noise_scale_ratio` is normally negative, because a bigger fire has
## COARSER grain, not more of the same grain.
##
## For reference at the shipped defaults: 200 stacks is `log(200) = 5.3`, 40 stacks is 3.7, 12 is
## 2.5. `fx_editor`'s `fire_stacks` slider is how these are judged.
@export_range(0.0, 1.0, 0.01) var intensity_ratio : float = 0.25
@export_range(0.0, 1.0, 0.01) var height_ratio : float = 0.16
## ⚠ NEGATIVE, and deliberately: a bigger fire is a MORE SOLID one, and the aperture is a CUT — so
## it has to fall as the count rises, not climb. This sign was wrong in the first build.
@export_range(-0.5, 1.0, 0.01) var aperture_ratio : float = -0.08
@export_range(-0.5, 1.0, 0.01) var gain_ratio : float = 0.05
@export_range(-0.5, 1.0, 0.01) var noise_scale_ratio : float = -0.06
@export_range(-0.5, 1.0, 0.01) var noise_scroll_ratio : float = 0.12

@export_group("Colour")
## The effect's whole palette, as an ORDERED LIST OF PALETTE ENTRIES (T21). u = heat, v = stack
## level; hard pixel columns are what read as pixel art, so it is sampled with filter_nearest, and a
## cold ramp makes this same shader frost.
##
## The texture is BUILT from this ramp at load — it used to be a PNG baked by tools/make_fx_ramp.py
## from two band tables interpolated per row, which is why the shipped fire ramp had 64 colours and
## not one of them was in the palette. Retuning fire is now editing an Array[int] in the inspector.
@export var ramp_source : PaletteRamp = null:
	set(value):
		ramp_source = value
		_ramp_tex = null
## How many of the ramp's entries one flame shows at once. The window SLIDES toward the hot end as
## the stack level rises (owner 2026-07-28: *"ramp could have 10 colors, and fire ramp can focus on
## window of 3 and move through the ramp when intensity increases"*), so more stacks means hotter
## bands rather than the same bands brightened.
@export_range(1, 12, 1) var ramp_window : int = 4:
	set(value):
		ramp_window = value
		_ramp_tex = null
## Heat thresholds where the window's bands change, one per band. Empty spaces them evenly.
@export var ramp_edges : PackedFloat32Array = PackedFloat32Array():
	set(value):
		# Coerced: the editor wrote `ramp_edges = null` into fire_card.tres once, while this script
		# was still a PLACEHOLDER there (it was not @tool), and a null would then crash the ramp
		# build on load. Cheap insurance against a corrupt .tres reaching the shader.
		ramp_edges = value if value != null else PackedFloat32Array()
		_ramp_tex = null
## Below this heat the flame is TRANSPARENT — the cut that gives the fire its ragged outline, so it
## belongs to the ramp rather than being a constant buried in the shader. ⚠ It matters MORE than it
## did: with no arch outline, the flame's silhouette is entirely "where does noise x cover cross
## this line".
@export_range(0.0, 0.9, 0.01) var ramp_cut : float = 0.18:
	set(value):
		ramp_cut = value
		_ramp_tex = null
## The stack count that reaches the TOP of the ramp. Normalization is logarithmic, so most of
## the ramp is spent on the first ~20 stacks — where the game actually lives — while still
## showing a difference all the way up (owner ruling 19: "a high number like 100+").
@export var level_ref : float = 120.0
## Pushes heat UP the ramp: more of the flame reaches the hotter bands. This is the lever
## surplus stacks feed. There is nothing to sprout more of any more (owner ruling 4).
@export var intensity : float = 1.0

## Cached build of `ramp_source`. Styles are shared preloads, so this is one texture per style for
## the whole run; every setter above drops it so an inspector edit rebuilds on the next apply().
var _ramp_tex : ImageTexture = null

## The heat/level ramp texture, built from `ramp_source` on first use and cached. Null ramp means the
## effect has no colours at all, which is a broken style rather than a supported state.
func ramp_texture() -> ImageTexture:
	if _ramp_tex: return _ramp_tex
	if not ramp_source: return null
	_ramp_tex = ramp_source.window_texture(ramp_window, 16, ramp_edges, ramp_cut)
	return _ramp_tex

## Write every fire lever onto a material, on top of the shared ones. Called on creation and on style
## swap, NEVER per frame.
##
## ⚠ The knobs that carry a stack ratio are written here too, at their BASE value, and
## `FxFire.stacks_live` then overwrites them per frame with the scaled one. That is deliberate: a
## host with no live values (the FX editor's static preview, a style swap mid-frame) still gets a
## sane flame rather than a zero.
func apply(mat: ShaderMaterial) -> void:
	super(mat)
	mat.set_shader_parameter(&"u_dither", dither)
	mat.set_shader_parameter(&"u_height", height)
	mat.set_shader_parameter(&"u_taps", cover_taps)
	mat.set_shader_parameter(&"u_cover_dither", cover_dither)
	mat.set_shader_parameter(&"u_sink", sink)
	mat.set_shader_parameter(&"u_inner_alpha", inner_alpha)
	mat.set_shader_parameter(&"u_aperture", aperture)
	mat.set_shader_parameter(&"u_fire_gain", fire_gain)
	mat.set_shader_parameter(&"u_skew", skew)
	mat.set_shader_parameter(&"u_pulse_amp", pulse_amp)
	mat.set_shader_parameter(&"u_pulse_speed", pulse_speed)
	mat.set_shader_parameter(&"u_lag_amount", lag_amount)
	mat.set_shader_parameter(&"u_wind", wind)
	mat.set_shader_parameter(&"u_noise_amp", noise_amp)
	mat.set_shader_parameter(&"u_noise_scale", noise_scale)
	mat.set_shader_parameter(&"u_noise_scroll", noise_scroll)
	mat.set_shader_parameter(&"u_noise_ratio", noise_ratio)
	mat.set_shader_parameter(&"u_flicker_speed", flicker_speed)
	mat.set_shader_parameter(&"u_noise_procedural", 1 if noise_procedural else 0)
	mat.set_shader_parameter(&"u_noise_tex", noise_tex if noise_tex else NOISE_TILE)
	mat.set_shader_parameter(&"u_noise_tile", maxf(noise_tile, 1e-3))
	mat.set_shader_parameter(&"u_ramp", ramp_texture())
