extends Resource
class_name Deck

func get_deck() -> Array[CardData]:
	return deck9

func get_rules() -> Array[CardData]:
	return rules1

## Every starter deck for the menu deck picker: [{name: String, cards: Array[CardData]}].
func get_deck_list() -> Array[Dictionary]:
	var list : Array[Dictionary] = []
	var decks : Array = [deck1, deck2, deck3, deck4, deck5, deck6, deck7, deck8, deck9, deck10]
	for i in decks.size():
		list.append({"name": "Deck %d" % (i + 1), "cards": decks[i]})
	return list


var rules1: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputUpper.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputUpper.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputUpper.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputUpper.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputUpper.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),

	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillAdderInputLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	
	CardData.new().with_type(TypePaper.new()).with_skill(SkillGrabberOgLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillPlacerOgLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillScorerCascadeLower.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),
	CardData.new().with_type(TypePaper.new()).with_skill(SkillEvalPokerBest.new()).with_suit(PipSuit.random_standard()).with_rank(PipRankNumeral.new().with_random()),

]

var deck1: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(2)),
	]

var deck2: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck3: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeHeavy.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck4: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(5)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(6)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(7)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(8)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(9)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(10)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(11)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(12)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(13)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(5)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(6)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(7)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(8)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(9)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(10)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(11)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(12)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(13)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(5)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(6)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(7)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(8)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(9)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(10)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(11)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(12)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(13)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(3)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(5)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(6)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(7)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(8)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(9)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(10)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(11)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(12)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(13)),
	]

var deck5: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	#CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck6: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(10)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(10)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(10)).with_skill(SkillHungryHippo.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(10)).with_skill(SkillHungryHippo.new()),
	]

var deck7: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck8: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillEchoingTrigger.new()).with_stamp(StampGlobal.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck9: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(1)).with_skill(SkillExtraPoint.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(2)).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(2)),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(3)).with_rank(PipRankNumeral.new().with_value(1)),
	]

var deck10: Array[CardData] = [
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(2)).with_rank(PipRankNumeral.new().with_value(3)).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(0)).with_rank(PipRankNumeral.new().with_value(4)).with_skill(SkillExtraPoint.new()).with_type(TypeStone.new()),
	CardData.new().with_type(TypePaper.new()).with_suit(PipSuit.from_index(1)).with_rank(PipRankNumeral.new().with_value(3)).with_stamp(StampRevealing.new()).with_type(TypeStone.new()),
	]
