extends Resource
class_name Deck



var deck1: Array[CardData] = [
	CardData.new().with_suit(1).with_rank(1),
	CardData.new().with_suit(2).with_rank(1),
	CardData.new().with_suit(3).with_rank(1),
	CardData.new().with_suit(4).with_rank(1),
	CardData.new().with_suit(1).with_rank(2),
	CardData.new().with_suit(2).with_rank(2),
	CardData.new().with_suit(3).with_rank(2),
	CardData.new().with_suit(4).with_rank(2),
	]

var deck2: Array[CardData] = [
	CardData.new().with_suit(1).with_rank(1),
	CardData.new().with_suit(2).with_rank(2),
	CardData.new().with_suit(3).with_rank(3),
	CardData.new().with_suit(4).with_rank(4),
	CardData.new().with_suit(1).with_rank(4),
	CardData.new().with_suit(2).with_rank(3),
	CardData.new().with_suit(3).with_rank(2),
	CardData.new().with_suit(4).with_rank(1),
	]

var deck3: Array[CardData] = [
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillExtraPoint.new()),
	CardData.new().with_suit(2).with_rank(2).with_stamp(StampRevealing.new()),
	CardData.new().with_suit(3).with_rank(3).with_type(TypeHeavy.new()),
	CardData.new().with_suit(4).with_rank(4).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_suit(1).with_rank(4).with_skill(SkillExtraPoint.new()).with_type(TypeHeavy.new()),
	CardData.new().with_suit(2).with_rank(3).with_stamp(StampRevealing.new()).with_type(TypeHeavy.new()),
	CardData.new().with_suit(3).with_rank(2),
	CardData.new().with_suit(4).with_rank(1),
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillExtraPoint.new()),
	CardData.new().with_suit(2).with_rank(2).with_stamp(StampRevealing.new()),
	CardData.new().with_suit(3).with_rank(3).with_type(TypeHeavy.new()),
	CardData.new().with_suit(4).with_rank(4).with_skill(SkillExtraPoint.new()).with_stamp(StampRevealing.new()),
	CardData.new().with_suit(1).with_rank(4).with_skill(SkillExtraPoint.new()).with_type(TypeHeavy.new()),
	CardData.new().with_suit(2).with_rank(3).with_stamp(StampRevealing.new()).with_type(TypeHeavy.new()),
	CardData.new().with_suit(3).with_rank(2),
	CardData.new().with_suit(4).with_rank(1),
	]

var deck4: Array[CardData] = [
	CardData.new().with_suit(1).with_rank(1),
	CardData.new().with_suit(1).with_rank(2),
	CardData.new().with_suit(1).with_rank(3),
	CardData.new().with_suit(1).with_rank(4),
	CardData.new().with_suit(1).with_rank(5),
	CardData.new().with_suit(1).with_rank(6),
	CardData.new().with_suit(1).with_rank(7),
	CardData.new().with_suit(1).with_rank(8),
	CardData.new().with_suit(1).with_rank(9),
	CardData.new().with_suit(1).with_rank(10),
	CardData.new().with_suit(1).with_rank(11),
	CardData.new().with_suit(1).with_rank(12),
	CardData.new().with_suit(1).with_rank(13),
	CardData.new().with_suit(2).with_rank(1),
	CardData.new().with_suit(2).with_rank(2),
	CardData.new().with_suit(2).with_rank(3),
	CardData.new().with_suit(2).with_rank(4),
	CardData.new().with_suit(2).with_rank(5),
	CardData.new().with_suit(2).with_rank(6),
	CardData.new().with_suit(2).with_rank(7),
	CardData.new().with_suit(2).with_rank(8),
	CardData.new().with_suit(2).with_rank(9),
	CardData.new().with_suit(2).with_rank(10),
	CardData.new().with_suit(2).with_rank(11),
	CardData.new().with_suit(2).with_rank(12),
	CardData.new().with_suit(2).with_rank(13),
	CardData.new().with_suit(3).with_rank(1),
	CardData.new().with_suit(3).with_rank(2),
	CardData.new().with_suit(3).with_rank(3),
	CardData.new().with_suit(3).with_rank(4),
	CardData.new().with_suit(3).with_rank(5),
	CardData.new().with_suit(3).with_rank(6),
	CardData.new().with_suit(3).with_rank(7),
	CardData.new().with_suit(3).with_rank(8),
	CardData.new().with_suit(3).with_rank(9),
	CardData.new().with_suit(3).with_rank(10),
	CardData.new().with_suit(3).with_rank(11),
	CardData.new().with_suit(3).with_rank(12),
	CardData.new().with_suit(3).with_rank(13),
	CardData.new().with_suit(4).with_rank(1),
	CardData.new().with_suit(4).with_rank(2),
	CardData.new().with_suit(4).with_rank(3),
	CardData.new().with_suit(4).with_rank(4),
	CardData.new().with_suit(4).with_rank(5),
	CardData.new().with_suit(4).with_rank(6),
	CardData.new().with_suit(4).with_rank(7),
	CardData.new().with_suit(4).with_rank(8),
	CardData.new().with_suit(4).with_rank(9),
	CardData.new().with_suit(4).with_rank(10),
	CardData.new().with_suit(4).with_rank(11),
	CardData.new().with_suit(4).with_rank(12),
	CardData.new().with_suit(4).with_rank(13),
	]

var deck5: Array[CardData] = [
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillExtraPoint.new()),
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillExtraPoint.new()).with_stamp(StampDoubleTrigger.new()),
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_suit(1).with_rank(1).with_skill(SkillEchoingTrigger.new()),
	CardData.new().with_suit(1).with_rank(1),
	#CardData.new().with_suit(1).with_rank(1),
	]

@export var card_datas : Array[CardData] = deck5
